/*
 * Software License Agreement (MIT License)
 *
 * Copyright (c) 2017, DUKELEC, Inc.
 * All rights reserved.
 *
 * Author: Duke Fong <d@d-l.io>
 */

#ifndef __CD_CONFIG_H__
#define __CD_CONFIG_H__

#define CDCTL_OSC_CLK       16000000UL // 16MHz

#define CD_ARCH_SPI

#define CD_DEBUG
//#define CD_VERBOSE
//#define CD_LIST_DEBUG
#define CD_DBG_STR_LEN      160

#define CD_LIST_IT
//#define CD_IRQ_SAFE
//#define CDN_IRQ_SAFE

//#define CDN_L0_C

#include "main.h"  // generated by stm32cube
#include "debug_config.h"

#endif
